services:
  - type: web
    name: wineshop-backend
    env: python
    region: ohio
    plan: free
    repo: https://github.com/ayyappachowdary04/inventory-tool.git
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false # Requires manual setup in dashboard
      - key: FRONTEND_URL
        sync: false # Requires manual setup in dashboard or replace with url
      - key: PYTHON_VERSION
        value: 3.10.0
